spring:
  datasource:
    url: jdbc:postgresql://xxxxxxxxxx.xxxxxxxxxx.us-east-1.rds.amazonaws.com:5432/xxxxxxxx
    username: xxxxxxxxxx
    password: xxxxxxxxx
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 5000

application:
  cors:
    allowed-origins: "**"
    allowed-methods: GET, POST, PUT, DELETE
  security:
    jwt:
      secret-key: xxxxxxxxxx
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  aws:
    region: us-east-1
    s3:
      bucket-name: hipicon-case-study
    credentials:
      access-key: xxxxxxxxxx
      secret-key: xxxxxxxxxx